$(document).ready(function(){
	$("").click(function(){
		$("").hide(2000);
	});
});
$(document).ready(function(){
	$("").hover(function(){
		$("").hide(2000);
	});
});
$(document).ready(function(){
	$("").append(function(){
		$("").hide(2000);
	});
});
$(document).ready(function(){
	$("").attr(function(){
		$("").hide(2000);
	});
});
$(document).ready(function(){
	$("").animet(function(){
		$("").hide(2000);
	});
});